from properties import OILS

my_oils = [OILS.BERGAMOT, OILS.ORANGE, OILS.GRAPEFRUIT, OILS.ROSEMARY, OILS.MYRTLE, OILS.SPEARMINT,  OILS.YLANG_YLANG,
           OILS.EUCALYPTUS, OILS.GERANIUM, OILS.TEA_TREE, OILS.LEMONGRASS, OILS.LAVANDER,
           OILS.PATCHOULI, OILS.CLOVE_LEAF,
           OILS.VERIVER, OILS.BASIL, OILS.MYRHH, OILS.ROSE, OILS.JASMINE, OILS.CEDARWOOD, OILS.ROMAN_CAMOMILE, OILS.TANGERINE,
           OILS.CINNAMON_LEAF, OILS.FRANKINCENSE, OILS.SANDALWOOD, OILS.GINGER]


dennis_oils = [OILS.BERGAMOT, OILS.SPEARMINT, OILS.TANGERINE,
           OILS.EUCALYPTUS,  OILS.ROMAN_CAMOMILE, OILS.BASIL, OILS.MYRHH]